# Generated by Django 5.2.5 on 2026-02-15 11:32

from django.db import migrations


def forward(apps, schema_editor):
    List = apps.get_model("base", "List")

    List.objects.create(name="groceries")


def backward(apps, schema_editor):
    List = apps.get_model("base", "List")

    List.objects.filter(name="groceries").delete()    


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [migrations.RunPython(forward, backward)]
